DotNetCore/MVCApp/MVCApp/Models/BaseEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCApp.Models
{
    public abstract class BaseEntity
    {
        public virtual int Id { get; set; }
    }
}

DotNetCore/MVCApp/MVCApp/Models/ErrorViewModel.cs
using System;

namespace MVCApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DotNetCore/MVCApp/MVCApp/Models/EventData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MVCApp.Models
{
    public class EventData : BaseEntity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public override int Id { get; set; }

        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Location cannot be empty")]
        public string Location { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime StartDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime EndDate { get; set; }

        [Required(ErrorMessage = "Speaker name is required")]
        public string Speaker { get; set; }

        [Required(ErrorMessage = "Registration link cannot be empty")]
        [Display(Name = "Registration Link")]
        [DataType(DataType.Url, ErrorMessage = "Invalid url fromat")]
        public string Url { get; set; }
    }
}

DotNetCore/MVCApp/MVCApp/Models/EventUser.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MVCApp.Models
{
    public class EventUser : BaseEntity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public override int Id { get; set; }

        //[HiddenInput(DisplayValue = false)]
        public int EventId { get; set; }

        [Display(Name = "Fisrt Name")]
        [Required(ErrorMessage = "FisrtName is required!.")]
        public string FisrtName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "LastName isrequired!.")]
        public string LastName { get; set; }

        [Display(Name = "Company Name")]
        [Required(ErrorMessage = "Company is required!.")]
        public string Company { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number required!.")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered phone format is not valid.")]
        public string ContactNo { get; set; }

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Email is required!.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        //[RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }

    }
}

DotNetCore/MVCApp/MVCApp/Controllers/EventInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCApp.Services;
using MVCApp.Repositories;
using MVCApp.Models;

namespace MVCApp.Controllers
{
    [Route("events")]
    public class EventInfoController : Controller
    {
        //private IEventManager eventManager;
        //public EventInfoController(IEventManager em)
        //{
        //    this.eventManager = em;
        //}        

        //[HttpGet("",Name = "EventList")]
        //public IActionResult Index()
        //{
        //    var events = eventManager.GetEvents();
        //    return View(events);
        //}

        //[HttpGet("new", Name ="NewEvent")]
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //[HttpPost("new",Name ="NewEvent")]
        //public IActionResult Create(EventData model)
        //{
        //    if(ModelState.IsValid)
        //    {
        //        eventManager.Add(model);
        //        return RedirectToRoute("EventList");
        //    }
        //    else
        //    {
        //        return View();
        //    }
        //}

        private IEventRepository<EventData> repo;
        private IEventRepository<EventUser> repo1;
        public EventInfoController(IEventRepository<EventData> repository, IEventRepository<EventUser> repository1)
        {
            this.repo = repository;
            this.repo1 = repository1;
        }

        [HttpGet("", Name = "EventList")]
        public IActionResult Index()
        {
            var events = repo.GetAll();
            return View(events);
        }

        [HttpGet("new", Name = "NewEvent")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("new", Name = "NewEvent")]
        public async Task<IActionResult> Create(EventData model)
        {
            if (ModelState.IsValid)
            {
                await repo.Add(model);
                return RedirectToRoute("EventList");
            }
            else
            {
                return View();
            }
        }


        [HttpGet("newevent", Name = "NewEventRegister")]
        public IActionResult EventRegister([FromQuery] int id)
        {
            var item = repo.Get(id);
            ViewBag.EventID = item.Id;
            ViewBag.EventName = item.Title;
            return View();
        }

        [HttpPost("newevent", Name = "NewEventRegister")]
        public async Task<IActionResult> EventRegister(EventUser model)
        {
            if (ModelState.IsValid)
            {
                await repo1.Add(model);
                return RedirectToRoute("EventList");
            }
            else
            {
                return View();
            }
        }
    }
}

DotNetCore/MVCApp/MVCApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCApp.Models;

namespace MVCApp.Controllers
{
    [Route("/home")]
    public class HomeController : Controller
    {
        //GET /home/
        [HttpGet("", Name = "Index")]
        public IActionResult Index()
        {
            return View();
        }

        //GET /home/privacy
        [HttpGet("privacy", Name = "privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DotNetCore/MVCApp/MVCApp/Views/EventInfo/Create.cshtml
@model MVCApp.Models.EventData

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>EventData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Speaker" class="control-label"></label>
                <input asp-for="Speaker" class="form-control" />
                <span asp-validation-for="Speaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DotNetCore/MVCApp/MVCApp/Views/EventInfo/EventRegister.cshtml
@model MVCApp.Models.EventUser

@{
    ViewData["Title"] = "EventRegister";
}

<h1>EventRegister</h1>

<h4>EventUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EventRegister">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Event Name</label>
                <input readonly="readonly" value="@ViewBag.EventName" class="form-control" />
                <input asp-for="EventId" type="hidden" readonly="readonly" value="@ViewBag.EventID" class="form-control" />
            </div>
            @*<div class="form-group">
                    <label asp-for="EventName" class="control-label"></label>
                    <input asp-for="EventName" class="form-control" />
                    <span asp-validation-for="EventName" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="FisrtName" class="control-label"></label>
                <input asp-for="FisrtName" class="form-control" />
                <span asp-validation-for="FisrtName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNo" class="control-label"></label>
                <input asp-for="ContactNo" class="form-control" />
                <span asp-validation-for="ContactNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DotNetCore/MVCApp/MVCApp/Views/EventInfo/Index.cshtml
@model IEnumerable<MVCApp.Models.EventData>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="EventRegister">Event Register</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Speaker)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    <a asp-action="EventRegister" asp-route-id="@item.Id" > @Html.DisplayFor(modelItem => item.Title)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Speaker)
                </td>
                <td>
                    <register url="@item.Url" />
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

DotNetCore/MVCApp/MVCApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotNetCore/MVCApp/MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EventInfo" asp-action="Index">Events</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>